# Site settings
title: "Julien Goulesque"
name: "Julien Goulesque"
description: "PhD Candidate in International Economics"
url: "https://jgoulesque.github.io"
baseurl: ""

# Author info (populates the sidebar)
author:
  name: "Julien Goulesque"
 # avatar: "images/profile.jpg"  # add a photo later
  bio: "PhD Candidate in International Economics (BxSE - Université de Bordeaux)"
  email: "julien.goulesque@u-bordeaux.fr"
  # Academic links:
  orcid: "https://orcid.org/0009-0001-2881-3906"
  # Add/remove as needed: twitter, linkedin, researchgate, etc.